apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventos-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eventos
  template:
    metadata:
      labels:
        app: eventos
    spec:
      containers:
        - name: eventos
          image: eventos-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: eventos-secret
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: eventos-config
                  key: APP_PORT
