apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventos-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventos-postgres
  template:
    metadata:
      labels:
        app: eventos-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: eventos-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventos-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: eventsdb
