apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
stringData:
  SUPABASE_SERVICE_ROLE_KEY: "xxx"
  FIREBASE_SERVICE_ACCOUNT_JSON: |
    {
      "type": "xxx",
      "project_id": "xxx",
      "private_key_id": "xxx",
      "private_key": "xxx",
      "client_email": "xxx",
      "client_id": "xxx",
      "auth_uri": "xxx",
      "token_uri": "xxx",
      "auth_provider_x509_cert_url": "xxx",
      "client_x509_cert_url": "xxx",
      "universe_domain": "xxx"
    }
